---
siteMetadata:
  siteTitle: Best Skoda Site
  siteTitleShort: Skoda Site
  siteDescription: An opinionated starter for Best Skoda Site
  siteUrl: https://gu.fabianschultz.com
  themeColor: '#000'
mainNavConfig:
  - href: /model/kodiaq
    title: Kodiaq
  - href: /model/octavia
    title: Octavia
