---
site_metadata:
  siteTitle: Best Skoda Site
  siteTitleShort: Skoda Site
  siteDescription: An opinionated starter for Best Skoda Site
  siteUrl: https://gu.fabianschultz.com
  themeColor: '#000'
