mainNavconfig:
  - href: qwe1
    title: qwe
siteMetadata:
  siteDescription: An opinionated starter for Best Skoda Site
  siteTitle: Best Skoda Site
  siteTitleShort: Skoda Site
  siteUrl: 'https://gu.fabianschultz.com'
  themeColor: '#000'
